### ISSUE TITLE
HDF5 versions mismatch :- TypeError: Internal error : invalid id from h5py !

### ISSUE THREAD

**Issue by santoshkumarradha** [conda-forge/triqs-feedstock#12]
Issue:

HDF5 version mismatch between h5py and hdf5. 

example error:
```python
from pytriqs.archive import HDFArchive
from pytriqs.gf import GfImFreq
G = GfImFreq ( indices = [1], beta = 10, n_points = 100)
H = HDFArchive('error-example.h5', 'w')
H['g'] = G
```
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/srr70/miniconda3/envs/triqs/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 194, in __setitem__
    for n,v in d.items() : SUB[n] = v
  File "/home/srr70/miniconda3/envs/triqs/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 184, in __setitem__
    val.__write_hdf5__(self._group,key)
TypeError: Internal error : invalid id from h5py !
```
<br/>
Environment (<code>conda list</code>):
<details>

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
apipkg                    1.5                        py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports_abc             0.5                        py_1    conda-forge
binutils_impl_linux-64    2.34                 h2122c62_8    conda-forge
binutils_linux-64         2.34                h47ac705_21    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
execnet                   1.7.1                      py_0    conda-forge
fftw                      3.3.8           mpi_openmpi_h6dd7431_1011    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
gcc_impl_linux-64         7.5.0               hda68d29_10    conda-forge
gcc_linux-64              7.5.0               ha781d05_21    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gxx_impl_linux-64         7.5.0               h64c220c_10    conda-forge
gxx_linux-64              7.5.0               ha781d05_21    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_102    conda-forge
hdf5                      1.10.5          mpi_openmpi_hac320be_1004    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
kernel-headers_linux-64   2.6.32              h77966d4_12    conda-forge
kiwisolver                1.1.0            py27h9e3301b_1    conda-forge
ld_impl_linux-64          2.34                 hc38a660_8    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  10.0.1          default_hde54327_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0               hdf63c60_10    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_0    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
linecache2                1.0.0                      py_1    conda-forge
mako                      1.1.0                      py_0    conda-forge
markupsafe                1.1.1            py27hdf8410d_1    conda-forge
matplotlib-base           2.2.5            py27h250f245_1    conda-forge
mock                      2.0.0                 py27_1001    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py27h9ab638b_1    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
nfft                      3.5.1                h46ee950_0    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openmpi                   4.0.4                hdf1f1ad_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
path.py                   10.3.1                   py27_0    conda-forge
pbr                       5.4.5              pyh9f0ad1d_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pytest                    3.2.2                      py_0    conda-forge
pytest-shutil             1.7.0                      py_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
sysroot_linux-64          2.12                h77966d4_12    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
triqs                     2.2.2            py27ha6da3d6_3    conda-forge
triqs_cthyb               2.2.1            py27h4ff3246_1    conda-forge
triqs_dft_tools           2.2.1            py27h490b6c0_2    conda-forge
triqs_tprf                2.2.0            py27h8c711b1_2    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : triqs
    active env location : /home/srr70/miniconda3/envs/triqs
            shell level : 1
       user config file : /home/srr70/.condarc
 populated config files : /home/srr70/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /home/srr70/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/abinit/linux-64
                          https://conda.anaconda.org/abinit/noarch
                          https://conda.anaconda.org/matsci/linux-64
                          https://conda.anaconda.org/matsci/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/srr70/miniconda3/pkgs
                          /home/srr70/.conda/pkgs
       envs directories : /home/srr70/miniconda3/envs
                          /home/srr70/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/3.10.0-1127.13.1.el7.x86_64 rhel/7.8 glibc/2.17
                UID:GID : 885540:10001
             netrc file : None
           offline mode : False
```
</details>

**Comment by Wentzell** [comment]
Dear @santoshkumarradha,

The latest release of triqs (2.2.2) is only compatible against Python 2.
From your conda info I see that you are using a Python3 based conda environment.
Can you try the same test using a Python2 based conda environment?

Note that the release of TRIQS 3.0 is close-by and we will make sure to generate
a conda-forge package shortly after the release.

**Comment by santoshkumarradha** [comment]
Hi @Wentzell 

Thanks for the quick reply. It is indeed true that the Conda is version 3 python, but the virtual environment is python 2.7 (as seen from Conda list inside virtual env). I did a clean environment with just Conda TRIQS installation. In fact I have no problem running the code without saving with HDF5. I am able to save custom objects inside HDF5 files using HDF5archiv just not the greens function. 

The error seems to steam from triqs/cpp2py_converters/h5.hpp
Line44 : if (!H5Iis_valid(id)) RAISE("Internal error : invalid id from h5py !");

Judging by the discussions in https://github.com/TRIQS/triqs/issues/353, seems to be a HDF5 version mismatch. 

PS: TRIQS for python 3 is a dream come true! Thanks a bunch. Any rough eta?

**Comment by Wentzell** [comment]
Dear @santoshkumarradha,

Yes we have observed the problem you mention when h5py and hdf5 mismatch.
We have however not observed the problem for conda so far.
Were you able to reproduce the problem on multiple machines?

Using a fresh conda + triqs setup generated using [Miniconda2](https://repo.anaconda.com/miniconda/Miniconda2-latest-MacOSX-x86_64.sh) your example runs without problems

<details><summary>conda info</summary>
<p>

```
     active environment : base
    active env location : /mnt/home/wentzell/miniconda2
            shell level : 1
       user config file : /mnt/home/wentzell/.condarc
 populated config files : /mnt/home/wentzell/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.15.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.17
       base environment : /mnt/home/wentzell/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/home/wentzell/miniconda2/pkgs
                          /mnt/home/wentzell/.conda/pkgs
       envs directories : /mnt/home/wentzell/miniconda2/envs
                          /mnt/home/wentzell/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/2.7.15 Linux/3.10.0-1062.9.1.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 1142:1142
             netrc file : None
           offline mode : False
```
</p>
</details>

My triqs, h5py and hdf5 versions are list as 

```
triqs                     2.2.2            py27ha6da3d6_3    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_102    conda-forge
hdf5                      1.10.5          mpi_openmpi_hac320be_1004    conda-forge
```

Could you check if the h5py is in fact the one that you expect?
```
python -v -c "import h5py" 2>&1 | grep "/h5py"
```

Also you can check if the `libhdf5` agrees between triqs and h5py
```
ldd /home/srr70/miniconda3/envs/triqs/lib/python2.7/site-packages/h5py/h5z.so
ldd /home/srr70/miniconda3/envs/triqs/lib/libtriqs.so
```

Finally you could try to build h5py from source instead using
```
pip install --no-binary=h5py h5py
```

> PS: TRIQS for python 3 is a dream come true! Thanks a bunch. Any rough eta?

The release candidate will be tagged within a week from now.
The actual release should follow a few weeks after.
In fact h5py will no longer be a dependency.

**Comment by santoshkumarradha** [comment]
```
pip uninstall h5py
pip install --no-binary=h5py h5py 
```

Seemed to have done the trick. I guess there still must have been conflict with my outside python. Thanks a bunch.

Excited for the py3 update ! all the best.
